# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FileField(max_length=50, null=True, upload_to='', verbose_name='操作人姓名')),
                ('action', models.FileField(max_length=50, null=True, upload_to='', verbose_name='操作动作')),
                ('request', models.FileField(max_length=50, null=True, upload_to='', verbose_name='请求url')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
