# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20170928_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('version', models.SmallIntegerField(choices=[(0, '1.6版本'), (1, '1.7版本'), (2, '1.8版本')], default=0, verbose_name='版本号')),
                ('group', models.SmallIntegerField(choices=[(0, '运维组'), (1, '开发组'), (2, '美术组')], default=0, verbose_name='分组')),
            ],
        ),
    ]
