# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FileField(max_length=50, upload_to='', verbose_name='登录名')),
                ('pwd', models.FileField(upload_to='', verbose_name='密码')),
            ],
        ),
    ]
